# Site settings
author: Pedro David Garcia Lopez
title: U-turn
header-img: img/home-bg.png
email: reddevil_cero@hotmail.com
copyright_name: Pedro David Garcia Lopez
description: > # this means to ignore newlines until "baseurl:"
  My travel from lorry driver to Software Engineering 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  reddevilcero

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
